QUANTUM_PAINTER_ENABLE = no
QUANTUM_PAINTER_DRIVERS += gc9a01_spi
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
POINTING_DEVICE_ENABLE = no

KEY_OVERRIDE_ENABLE = yes
TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
COMBO_ENABLE = yes
